[project]
name = 'Supply-Chain-Transparency-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consumer-verification]
path = 'contracts/consumer-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.product-registration]
path = 'contracts/product-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-assurance]
path = 'contracts/quality-assurance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
